# DBscan experiment

```{r}
library(dbscan)
library(ggplot2)
```



# Make dbscan function
```{r}
db_clustering <- function(file_in, NumOfPts = 20){
  modified <- file_in[1:2]
  

  modified[modified == 0] <- NA
  
  for(i in 1:ncol(modified)){
    modified[is.na(modified[,i]), i] <- mean(modified[,i], na.rm = TRUE)
  }
  
  log_file <- log2(modified)
  
  scan <- hdbscan(x = log_file, minPts = NumOfPts, gen_hdbscan_tree = T, gen_simplified_tree = F)
  plot(log_file, col = scan$cluster +1, pch = 20)
  return(scan)
}

points_calc <- function(x){
  num_of_points <- length(x[,1])/100*1.5
  return(num_of_points)}

```


# Execute
```{r}
sample1 <- read.csv("../csvData/csvData3/Sample1/A01_Uncolored_PHBV_Before_freeze_thaw_Dilution10x_Sample01.fcs.csv")
sample2 <- read.csv("../csvData/csvData3/Sample1/A05_Uncolored_PHBV_After_freeze_thaw_Dilution10x_Sample01.fcs.csv")
sample3 <- read.csv("../csvData/Sample1_folder1.csv")

db_clustering(sample1, points_calc(sample1))
db_clustering(sample3, points_calc(sample3))
```



```{r}
A01.1 <- read.csv("../csvData/csvData1/Sample1/A01_AfterIncubation_d1000_S1,4.fcs.csv")
A02.1 <- read.csv("../csvData/csvData1/Sample1/A02_AfterIncubation_d1000_S1,4.fcs.csv")
A03.1 <- read.csv("../csvData/csvData1/Sample1/A03_AfterIncubation_d1000_S1,4.fcs.csv")
A04.1 <- read.csv("../csvData/csvData1/Sample1/A04_AfterIncubation_d1000_S1,4.fcs.csv")
A05.1 <- read.csv("../csvData/csvData1/Sample1/A05_AfterIncubation_d1000_S1,4.fcs.csv")
A06.1 <- read.csv("../csvData/csvData1/Sample1/A06_AfterIncubation_d1000_S1,4.fcs.csv")
A07.1 <- read.csv("../csvData/csvData1/Sample1/A07_AfterIncubation_d1000_S1,4.fcs.csv")
A08.1 <- read.csv("../csvData/csvData1/Sample1/A08_AfterIncubation_d1000_S1,4.fcs.csv")
A09.1 <- read.csv("../csvData/csvData1/Sample1/A09_AfterIncubation_d1000_S1,4.fcs.csv")
A10.1 <- read.csv("../csvData/csvData1/Sample1/A10_AfterIncubation_d1000_S1,4.fcs.csv")

E01.1 <- read.csv("../csvData/csvData1/Sample1/E01_AfterIncubation_d100_S1,3.fcs.csv")
E02.1 <- read.csv("../csvData/csvData1/Sample1/E02_AfterIncubation_d100_S1,3.fcs.csv")
E03.1 <- read.csv("../csvData/csvData1/Sample1/E03_AfterIncubation_d100_S1,3.fcs.csv")
E04.1 <- read.csv("../csvData/csvData1/Sample1/E04_AfterIncubation_d100_S1,3.fcs.csv")
E05.1 <- read.csv("../csvData/csvData1/Sample1/E06_AfterIncubationRediluded__d100_S1,3.fcs.csv")


A01.2 <- read.csv("../csvData/csvData2/Sample1/A01_Carl_d10x_S01.fcs.csv")
A02.2 <- read.csv("../csvData/csvData2/Sample1/A02_Carl_d10x_S01.fcs.csv")
A03.2 <- read.csv("../csvData/csvData2/Sample1/A03_Carl_d10x_S01.fcs.csv")
A04.2 <- read.csv("../csvData/csvData2/Sample1/A04_Carl_d10x_S01.fcs.csv")

E01.2 <- read.csv("../csvData/csvData2/Sample1/E01_FreezeThaw_d1000x_S01.fcs.csv")
E03.2 <- read.csv("../csvData/csvData2/Sample1/E03_FreezeThaw_d100x_S01.fcs.csv")
E05.2 <- read.csv("../csvData/csvData2/Sample1/E05_FreezeThaw_d10x_S01.fcs.csv")
E09.2 <- read.csv("../csvData/csvData2/Sample1/E09_FreezeThaw_d10x_S01.fcs.csv")
E10.2 <- read.csv("../csvData/csvData2/Sample1/E10_FreezeThaw_d10x_S01.fcs.csv")
E12.2 <- read.csv("../csvData/csvData2/Sample1/E12_FreezeThaw_d10x_S01.fcs.csv")


well_A_map1 <- rbind(A01.1, A02.1, A03.1, A04.1, A05.1, A06.1, A07.1, A08.1, A09.1, A10.1)
Well_E_map1 <- rbind(E01.1, E02.1, E03.1, E04.1, E05.1)
well_A_map2 <- rbind(A01.2, A02.2, A03.2, A04.2)
Well_E_map2 <- rbind(E01.2, E03.2, E05.2, E09.2, E10.2, E12.2)


q <- db_clustering(Well_E_map2, 15)
q$cluster_scores
```



