---
title: "End statistics"
author: "Rienk Heins"
date: '2022-05-31'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(factoextra)
library(dbscan)
library(ggplot2)
library(cluster)
library("fpc")
library("plyr")                                                 
library("readr")
```



# Make dbscan function
```{r}
db_clustering <- function(file_in, NumOfPts = 20){
  modified <- file_in[1:2]
  

  modified[modified == 0] <- NA
  
  for(i in 1:ncol(modified)){
    modified[is.na(modified[,i]), i] <- mean(modified[,i], na.rm = TRUE)
  }
  
  log_file <- log2(modified)
  
  scan <- hdbscan(x = log_file, minPts = NumOfPts, gen_hdbscan_tree = T, gen_simplified_tree = F)
  plot(log_file, col = scan$cluster +1, pch = 20)
  return(scan)
}

points_calc <- function(x){
  num_of_points <- length(x[,1])/100*1.5
  return(num_of_points)}
```


# Execute
```{r}
sample1 <- read.csv("../csvData/csvData3/Sample1/A01_Uncolored_PHBV_Before_freeze_thaw_Dilution10x_Sample01.fcs.csv")
sample2 <- read.csv("../csvData/csvData3/Sample1/A05_Uncolored_PHBV_After_freeze_thaw_Dilution10x_Sample01.fcs.csv")
sample3 <- read.csv("../csvData/Sample1_folder1.csv")

db1 <- db_clustering(sample1, points_calc(sample1))
db2 <- db_clustering(sample3, points_calc(sample2))
```

```{r}
sample1 <- cbind(sample1, db1$cluster)
sample1$`db1$cluster`
plot(y = log2(sample1$SSC.A), x = log2(sample1$FSC.A), col = sample1$`db1$cluster`)
legend(1, 95, col = sample1$`db1$cluster`, legend = "legend", lty=1:2, cex=0.8)
```

```{r}
sample2 <- cbind(sample2, db2$cluster)
```


```{r}
plot(x = log2(sample1[sample1$`db1$cluster` == 2, 'FSC.A']),y = log2(sample1[sample1$`db1$cluster` == 2, 'SSC.A']))
```


```{r}
mean(sample1[sample1$`db1$cluster` == 2, 'FSC.A'])
mean(sample1[sample1$`db1$cluster` == 2, 'FSC.H'])
mean(sample1[sample1$`db1$cluster` == 2, 'Width'])
```

# Map 3 and 4

```{r}
map3 <- list.files(path = "data/map3/sample01/",    
                       pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                                           
  bind_rows

map4 <- list.files(path = "data/map4/sample01/",    
                       pattern = "*csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                                           
  bind_rows 


map1 <- read.csv("data/Sample1_folder1.csv")
# map1 <- as.data.frame(map1)
map3 <- as.data.frame(map3)
map4 <- as.data.frame(map4)


```


# Create functions for statistics

```{r}
perc_shift <- function(x, y){
  return(((y-x)/x) * 100)
}

perc_clustered <- function(x, y){
  return((y/x) * 100)
}

cluster_vector <- function(x, y){
  return(c(x[1] - y[1], x[2] - y[2]))
}

silhouette_scores <- function(data_file){
  sil <- silhouette(data_file[,15], dist(data_file[, c(1:14)]))
  return(summary(sil))
}
```

# Usage of code

## Total points clustered
```{r}
total_points <- dim(sample1)[1]
points_clustered <- dim(sample1[sample1$`db1$cluster` == c(1, 2),])[1]
total_clustered <- perc_clustered(total_points, points_clustered)
total_clustered
```

## Silhouette score
```{r}
silhouette_scores(sample1)
```

## Cluster vectors
```{r}
center1 <- c(mean(sample1$FSC.A), mean(sample1$SSC.A))
center2 <- c(mean(sample2$FSC.A), mean(sample2$SSC.A))
cluster_vector(center1, center2)
```

## Forward and sideward scatter change
```{r}
perc_shift(mean(sample1$FSC.A), mean(sample2$FSC.A))
perc_shift(mean(sample1$FSC.H), mean(sample2$FSC.H))
perc_shift(mean(sample1$SSC.A), mean(sample2$SSC.A))
perc_shift(mean(sample1$SSC.H), mean(sample2$SSC.H))
```

```{r}
files <- list.files(path = "../csvData/csvData4/Sample1/")
Time0 <- data.frame()
for(i in 1:length(files)){
  csv_file <- paste("../csvData/csvData4/Sample1/", files[i], sep = "")
  Time0 <- rbind(Time0, read.csv(csv_file))
}

files <- list.files(path = "../csvData/csvData1/Sample1/")
Time1 <- data.frame()
for(i in 1:length(files)){
  csv_file <- paste("../csvData/csvData1/Sample1/", files[i], sep = "")
  Time1 <- rbind(Time1, read.csv(csv_file))
}

files <- list.files(path = "../csvData/csvData2/Sample1/")
Time2 <- data.frame()
for(i in 1:length(files)){
  csv_file <- paste("../csvData/csvData2/Sample1/", files[i], sep = "")
  Time2 <- rbind(Time2, read.csv(csv_file))
}

files <- list.files(path = "../csvData/csvData3/Sample1/")
Time3 <- data.frame()
for(i in 1:length(files)){
  csv_file <- paste("../csvData/csvData3/Sample1/", files[i], sep = "")
  Time3 <- rbind(Time3, read.csv(csv_file))
}
```

# Testing statistics on full datasets

clustering:
```{r}
db0 <- db_clustering(Time0, points_calc(Time0))
db1 <- db_clustering(Time1, points_calc(Time1))
db2 <- db_clustering(Time2, points_calc(Time2))
db3 <- db_clustering(Time3, points_calc(Time3))
```


## Silhouette scores
```{r}
silhouette_scores(Time0)
silhouette_scores(Time1)
silhouette_scores(Time2)
silhouette_scores(Time3)
```


