---
title: "Create pca data"
author: "Rienk Heins"
date: "5/9/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dbscan)
```

```{r}
data_file1 <- read.csv("~/bioplastic_degradation/csvData/csvData3/Sample1/A01_Uncolored_PHBV_Before_freeze_thaw_Dilution10x_Sample01.fcs.csv")
data_file1 <- data_file1[,c(1:13)]
data_file1
```

Normalization

```{r}
z_data <- sapply(data_file1, function(x) (x - mean(x)) / sd(x))
as.data.frame(z_data)
```

```{r}
log_norm <- sapply(data_file1, function(x) log2(x))
log_norm <- as.data.frame(log_norm)
plot(log_norm$FSC.A, log_norm$SSC.A)
```

OPTICS in R:

```{r}
res <- optics(log_norm, eps = 2, minPts = 10)
res
```

```{r}
plot(res)
```

```{r}
res <- extractDBSCAN(res, eps_cl = .9)
res
```

```{r}
x <- cbind(log_norm$FSC.H, log_norm$SSC.H)
```


```{r}
res <- extractDBSCAN(res, eps_cl = .9)
res
plot(res)
hullplot(x, res)
```


```{r}
write.csv(log_norm, "log2_norm_data_sample1.1.csv", row.names = FALSE)
```

Creating csv file:
```{r}
write.csv(z_data, "z_normalized_data_sample1.1.csv", row.names = FALSE)
```



