---
title: "Statistics"
author: "Rienk Heins"
date: '2022-06-13'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Functions:

```{r}
perc_shift <- function(x, y){
  return(((y-x)/x) * 100)
}

perc_clustered <- function(x, y){
  return((y/x) * 100)
}

cluster_vector <- function(x, y){
  vec <- c(x[1] - y[1], x[2] - y[2])
  return(sqrt(vec[1]^2 + vec[2]^2))
}

silhouette_scores <- function(data_file){
  sil <- silhouette(data_file[,15], dist(data_file[, c(1:14)]))
  return(summary(sil))
}
```


# Code
Dit zijn de waarden die naar csv moeten
```{r}
FSC.change <- perc_shift(mean("Dataset2$FSC.A voor cluster"), mean("Dataset1$FSC.A voor cluster"))

SSC.change <- perc_shift(mean("Dataset2$SSC.A voor cluster"), mean("Dataset1$SSC.A voor cluster"))

Width.chane <- perc_shift(mean("Dataset2$Width voor cluster"), mean("Dataset1$Width voor cluster"))

cluster_vector("Center cluster 2", "Center cluster 1")

total_points <- dim("dataset")[1]
points_clustered <- dim("alle geclusterde punten in dataset")[1]
total_clustered <- perc_clustered(total_points, points_clustered)

silhouette_score <- silhouette_scores("dataset")
```

