"""
Main script to execute
"""

configfile: "config/config.yaml"

rule all:
      input:
        "checks/download.done",
        "checks/convert.done",
        "checks/scan.done",
        "checks/stat.done"

          
include: "rules/convert.smk"
include: "rules/hdbscan.smk"
include: "rules/statistics.smk"
        
  
