---
title: "PCA"
author: "Pascal Visser"
date: "28-3-2022"
output: pdf_document
---

# load libraries

```{r}
library(ggplot2)
library(factoextra)
library(FactoMineR)
```


# load in the data


```{r}
A01 <- read.csv("csvData1/Sample1/A01_AfterIncubation_d1000_S1,4.fcs.csv")
A02 <- read.csv("csvData1/Sample1/A02_AfterIncubation_d1000_S1,4.fcs.csv")
A03 <- read.csv("csvData1/Sample1/A03_AfterIncubation_d1000_S1,4.fcs.csv")
A04 <- read.csv("csvData1/Sample1/A04_AfterIncubation_d1000_S1,4.fcs.csv")
A05 <- read.csv("csvData1/Sample1/A05_AfterIncubation_d1000_S1,4.fcs.csv")
A06 <- read.csv("csvData1/Sample1/A06_AfterIncubation_d1000_S1,4.fcs.csv")
A07 <- read.csv("csvData1/Sample1/A07_AfterIncubation_d1000_S1,4.fcs.csv")
A08 <- read.csv("csvData1/Sample1/A08_AfterIncubation_d1000_S1,4.fcs.csv")
A09 <- read.csv("csvData1/Sample1/A09_AfterIncubation_d1000_S1,4.fcs.csv")
A10 <- read.csv("csvData1/Sample1/A10_AfterIncubation_d1000_S1,4.fcs.csv")

A1 <- read.csv("csvData3/A01_Uncolored_PHBV_Before_freeze_thaw_Dilution10x_Sample01.fcs.csv")
A2 <- read.csv("csvData3/A02_Uncolored_PHBV_Before_freeze_thaw_Dilution10x_Sample01..fcs.csv")
A4 <- read.csv("csvData3/A04_Uncolored_PHBV_After_freeze_thaw_Dilution10x_Sample01..fcs.csv")
A5 <- read.csv("csvData3/A05_Uncolored_PHBV_After_freeze_thaw_Dilution10x_Sample01.fcs.csv")

F1 <- read.csv("csvData4/F01_Uncolored_FreshPHBV_d1x_S02.fcs.csv")
F2 <- read.csv("csvData4/F02_Uncolored_FreshPHBV_d1x_S02.fcs.csv")
F4 <- read.csv("csvData4/F04_Colored_FreshPHBV_d1x_S02.fcs.csv")
F5 <- read.csv("csvData4/F05_Colored_FreshPHBV_d1x_S02.fcs.csv")

total <- rbind(A01, A02, A03, A04, A05, A06, A07, A08, A09, A10)
total <- total[,-14]


totalx <- rbind(A4, A5)


totalf <- rbind(F4, F5)
totalf <- totalf[,c(1:2,7:8,13)]


A01
```

# make functions

```{r}
scree <- function(x) {
  pca_obj <- prcomp(x, center = T, scale = T)
  a <- fviz_eig(pca_obj, addlabels = T, ylim = c(0,100))
  PCA(x, scale.unit = T, ncp = 14, graph = T)
  return(a)
}
```



```{r}
scree(total)
```


```{r}
```



labels weghalen
meerere zinnige pca s maken
naast elkaar legge